[Interface]
PrivateKey = <HIDDEN>
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = xDt94krQm9glWHLUpnQBJ+/H81OIK+HZ6ag2uGjmeUY=
Endpoint = 192.168.0.200:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
